### ISSUE TITLE
Suggestion to correct some of the calculations in parse-spy.py

### ISSUE THREAD

**Issue by cgst** [florinel-chis/stocks#1]
It appears that `buyPrice` is intended to be the mean of `Low` and `High`, therefore the formula should be updated from:

```python
df['buyPrice'] = df['Low']+df['High']/2
```

to

```python
df['buyPrice'] = (df['Low']+df['High'])/2
```

Calculating `potentialProfit` appears to be incorrect because it's subtracting the sum of `buyPrice`, when the cost basis is actually `(dfBought['buyPrice'] * dfBought['positions']).sum()`.

**Comment by florinel-chis** [comment]
@cgst I should be ashamed *insert here ashamed icon*.
